spring:
  sql:
    init:
      mode: never
  application:
    name: AltaSoftTest
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: localhost
    port: 3025
    username: test
    password: test
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: true

camel:
  springboot:
    name: AltaSoftTestCamelApp

logging:
  level:
    org:
      apache:
        camel: DEBUG
      springframework:
        mail: DEBUG